### ISSUE TITLE
Byte slices are zeroed when transmitted

### ISSUE THREAD

**Issue by quantum1423** [lunixbochs/struc#15]
Basically, you cannot pack or unpack any struct containing variable-length `[]byte`. This is a crippling bug, and it's not pleasant to discover this only after writing 200 lines of protocol code! I'm pretty sure it won't be hard to fix, considering that strings are handled correctly.

Here's an example demonstrating this bug:

````
package main

import (
    "bytes"
    "fmt"
    "github.com/lunixbochs/struc"
)

type Example struct {
    A int `struc:"big"`

    // B will be encoded/decoded as a 16-bit int (a "short")
    // but is stored as a native int in the struct
    B int `struc:"int16"`

    // the sizeof key links a buffer's size to any int field
    Size int `struc:"int8,little,sizeof=Str"`
    Str  []byte

    // you can get freaky if you want
    Str2 string `struc:"[5]int64"`
}

func main() {
    var buf bytes.Buffer
    t := &Example{1, 2, 0, []byte("test"), "test2"}
    struc.Pack(&buf, t)
    o := &Example{}
    struc.Unpack(&buf, o)
    fmt.Println(t)
    fmt.Println(o)
}
````

The output of the program is 
````
&{1 2 0 [116 101 115 116] test2}
&{1 2 4 [0 0 0 0] test2}
````
but the two lines should be the same.

**Comment by lunixbochs** [comment]
Looks like a failure during Pack(), as `fmt.Println(buf.Bytes)` starts with `[0 0 0 1 0 2 4 0 0 0 0]`. Looking into this.

**Comment by lunixbochs** [comment]
The length field was 0 during Pack, which caused it to not encode the []byte field for some reason (even though it guessed the correct input buffer length).

I added a second check and a unit test for this. This *should* be handled by the Sizeof handler in field.Pack() for the length field, so I'll check that out and maybe simplify the code. Either way, there's a test specifically for this now.

**Comment by lunixbochs** [comment]
You're my first confirmed user, btw. Any feedback? What are you using it for?

**Comment by quantum1423** [comment]
I'm using it for https://github.com/KirisurfProject/sagiri which basically is a quite complex stack of protocols that ultimately implements an onion-routing system like Tor, but designed around greatly improving censorship resistance, and geared towards giving privacy support to applications rather than proxying the Internet. 

I've been using manual packing/unpacking of protocols, but it's very tedious and error-prone, and then I randomly discovered your thing. It's almost as good as the macro-based packer/unpackers that I've used in Racket (which unfortunately uses too much memory for my needs, and although it has goroutine-like cheap threads, it doesn't scale to multiple cores). Well, except that it doesn't actually work at the moment >_<
