### ISSUE TITLE
Allow setting multiple data fields for sizeof tag

### ISSUE THREAD

**Issue by c4milo** [lunixbochs/struc#28]

**Comment by lunixbochs** [comment]
Try sizefrom

**Comment by c4milo** [comment]
My bad, let me explain my use case better. I have a length field, if it is even, I need to do padding otherwise I don't need the padding. What would be the best way to handle this using struc?

**Comment by lunixbochs** [comment]
That's a weird case. Can you provide an example?

**Comment by c4milo** [comment]
ISO9660 -
http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-119.pdf

Section 9.1.12

**Comment by c4milo** [comment]
No worries, I think I'm going to remove padding from the structs and added manually when needed.
