### ISSUE TITLE
add `ignore` word to not consider a field when packing/unpacking

### ISSUE THREAD

**Issue by lunixbochs** [lunixbochs/struc#3]

**Comment by luckcolors** [comment]
any update on this?

**Comment by luckcolors** [comment]
So, i made a pull request about this, and i haven't seen problems while using this in my code.
Let me know what you think.

**Comment by lunixbochs** [comment]
Oh, `struc:"skip"` is already a thing.

**Comment by luckcolors** [comment]
@lunixbochs Oh, didn't know there was something already implemented.
Should i just delete my PR then?

**Comment by luckcolors** [comment]
We should also update the readme docs and add info about "skip".

**Comment by lunixbochs** [comment]
Yeah, the PR is redundant now but I'd love a docs PR :)
