### ISSUE TITLE
Support Weird Number Encodings

### ISSUE THREAD

**Issue by caffinatedmonkey** [lunixbochs/struc#35]
I've found numbers in network protocols which are 3 or 5 bytes long and decoding them is hard.

**Comment by lunixbochs** [comment]
Can you link to a protocol document or RFC describing these?

**Comment by caffinatedmonkey** [comment]
I'm trying to develop a client for Boom Beach. Information about the protocol used for this game and other games made by supercell [can be found here](//github.com/clanner/cocdp/wiki/Protocol). The length field is 3 bytes long (big endian). I've currently been decoding it by appending an empty byte to the front then converting it to an integer. I would like to use your library to handle all the encoding/decoding code but I can't because of this.

Thanks!

**Comment by lunixbochs** [comment]
I think the solution here is to support unknown types via custom `Pack()`, `Unpack()`, and `Sizeof()` methods, as per issue #4.

Maybe with signatures like this:

    func (t *Type) Pack(buf []byte, opt *struc.Options) error
    func (t *Type) Unpack(r io.Reader, opt *struc.Options) error
    func (t *Type) Sizeof(opt *struc.Options) error

Where `struc.Options` currently provides the machine's pointer size and Endianness.

Honestly I could also use this on some common types to get nice performance improvements by reducing reflection.

**Comment by caffinatedmonkey** [comment]
This sounds like a good way to make the library more usable and maintainable. I'm looking forward to the implementation.

**Comment by lunixbochs** [comment]
Try bdd8f0722f5e88fbacc44138bb69f0152b61655a

**Comment by caffinatedmonkey** [comment]
Thanks, but I can't seem to use the `Int3` type with a `sizeof`. For example, the following does not work, `Data` is of length zero and empty.

```
type Message struct {
    Length Int3 `struc:"sizeof=Data"`
    Data []byte `struc:"[]byte"`
}
```

**Comment by lunixbochs** [comment]
I added a unit test for `Int3` being used as a `sizeof` field and fixed a possible crash case with custom types as sizes.
