### ISSUE TITLE
Half Floats (float16)

### ISSUE THREAD

**Issue by lain-dono** [lunixbochs/struc#39]
[wiki: Half-precision floating-point format](https://en.wikipedia.org/wiki/Half-precision_floating-point_format)

``` go
type Point struct {
  X float64 `struc:"float16"`
  Y float64 `struc:"float16"`
}
```

**Comment by lunixbochs** [comment]
Should be a custom type like Int3 from here: https://github.com/lunixbochs/struc/issues/35

type Float16 float32
func (f *Float16) Pack(buf []byte, opt *struc.Options) error {
    // put *f into buf
    return nil
}
func (f *Float16) Unpack(r io.Reader, opt *struc.Options) error {
    var tmp [2]byte
    if _, err := r.Read(tmp[3]); err != nil {
        return err
    }
    // *f = unpack float
    return nil
}
func (f *Float16) Sizeof(opt *struc.Options) int {
    return 2
}

**Comment by lunixbochs** [comment]
You should be able to use the `struc.Float16` type for field values now. I'll need to do some plumbing before it's usable via `struc:"float16"` because that can't be used to specify completely custom types yet.

**Comment by 13rac1** [comment]
FWIW I consider this issue closeable.
