### ISSUE TITLE
Zero padded strings

### ISSUE THREAD

**Issue by abourget** [lunixbochs/struc#53]
Hi,

I was wondering if it'd be hard to build a `zeroed` flag or something, that would make this work:

```type Currency struct {
	Precision byte   `struc:"uint8"`
	Name      string `struc:"[7]uint8"`
}
```

the Name is 7 bytes, but it's zero padded at the end, I'd like to have the string without the zeroes, and pad back with zeroes when writing.. I tried `pad`.. but it seems to simply ignore the field, right ?

So the data: `0443555200000000` would deserialize to `Currency{4, "CUR"}` instead of `Currency{4, "CUR\x00\x00\x00\x00"}`.

**Comment by lunixbochs** [comment]
#42 #31 

Does it pack correctly? The easiest workaround for now is to trim nulls yourself using strings.TrimRight.

**Comment by abourget** [comment]
ok, thanks
