### ISSUE TITLE
Incorrect conversion of signed integers (when converting from lower to higher bit-size).

### ISSUE THREAD

**Issue by mewmew** [lunixbochs/struc#57]
When converting signed 32-bit integers to 64-bit integers, the sign is lost, and negative values are converted to their unsigned counterpart.

E.g. converting -1 from int32 to int64 results in 4294967295, when the correct result should be -1.

The following test case demonstrates this:

```diff
diff --git a/struc_test.go b/struc_test.go
index 6352634..5e18aba 100644
--- a/struc_test.go
+++ b/struc_test.go
@@ -38,6 +38,9 @@ type Example struct {
 	Float1 float32 // 41 a0 00 00
 	Float2 float64 // 41 35 00 00 00 00 00 00
 
+	I32f2 int64 `struc:"int32"`  // ff ff ff ff
+	U32f2 int64 `struc:"uint32"` // ff ff ff ff
+
 	Size int    `struc:"sizeof=Str,little"` // 0a 00 00 00
 	Str  string `struc:"[]byte"`            // "ijklmnopqr"
 	Strb string `struc:"[4]byte"`           // "stuv"
@@ -75,6 +78,8 @@ var reference = &Example{
 	1, 2, 3, 4, 5, 6, 7, 8, 0, []byte{'a', 'b', 'c', 'd'},
 	9, 10, 11, 12, 13, 14, 15, 16, true, false, [4]byte{'e', 'f', 'g', 'h'},
 	20, 21,
+	-1,
+	4294967295,
 	10, "ijklmnopqr", "stuv",
 	4, "1234",
 	4, []byte("5678"),
@@ -100,6 +105,9 @@ var referenceBytes = []byte{
 	65, 160, 0, 0, // real float32(20)
 	64, 53, 0, 0, 0, 0, 0, 0, // real float64(21)
 
+	255, 255, 255, 255, // fake int32(-1)
+	255, 255, 255, 255, // fake uint32(4294967295)
+
 	10, 0, 0, 0, // little-endian int32(10) sizeof=Str
 	'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', // Str
 	's', 't', 'u', 'v', // fake string([4]byte)
```

Note, the unsigned test passes the test case successfully. However, the signed test fails.

To merge the test case, either apply this patch, or find it in the `signedconv` branch at https://github.com/mewpull/struc/tree/signedconv

**Comment by lunixbochs** [comment]
https://github.com/lunixbochs/struc/blob/master/field.go#L102 - try changing to int64

**Comment by lunixbochs** [comment]
Nevermind, that's pack not unpack.

**Comment by lunixbochs** [comment]
Need a similar fix on unpack - https://github.com/lunixbochs/struc/blob/master/field.go#L225

```
case Int8: n = uint64(int8(buf[0]))
case Int16: n = uint64(int16(order.Uint16(buf)))
...etc
```

**Comment by lunixbochs** [comment]
I've been considering trying some shenanigans with field.Interface() and [argjoy's](https://github.com/lunixbochs/argjoy) type switch [codec](https://github.com/lunixbochs/argjoy/blob/master/codecs.go#L50) instead of using full reflection for basic types

**Comment by lunixbochs** [comment]
Since struc is currently a zero-dependency library, I'm kinda against adding a test-only dependency.

**Comment by mewmew** [comment]
> Since struc is currently a zero-dependency library, I'm kinda against adding a test-only dependency.

That's fair. I guess we could use the `fmt` library to print expected and wanted values? Or just leave it as is, and instrument the test cases when trouble-shooting some code.

**Comment by lunixbochs** [comment]
Using `fmt.Printf("%#v")` or `%+v` and requiring a manual diff is okay.

**Comment by mewmew** [comment]
> Using fmt.Printf("%#v") or %+v and requiring a manual diff is okay.

Done.
