### ISSUE TITLE
remaining portion of struct to string

### ISSUE THREAD

**Issue by atlantageek** [lunixbochs/struc#77]
I would like to request a new tag.  Some protocols I work with want the user to take the remaining portion of a struct and assign it to the last string.  Would it be possible to add that as a feature.

**Comment by lunixbochs** [comment]
Can you be more specific and provide an example?

**Comment by atlantageek** [comment]
I would like to be able to define something like this.
type connectIdl struct {
	IndicatorID       uint32
	InitiatorPort     uint16
	Capabilities      uint32
	KeepAliveInterval uint32
	VendorID          string `struc:"remaining"`
}

If the object being unpacked is 20 bytes long the VendorID would take up the last 6 bytes of the 20 byte object.

**Comment by lunixbochs** [comment]
Unpack uses an io.reader. There’s no such thing as the rest of the data.

**Comment by atlantageek** [comment]
Point taken. Thanks
