### ISSUE TITLE
Pack int as 3 bytes?

### ISSUE THREAD

**Issue by andig** [lunixbochs/struc#86]
I need to pack an int as 3 bytes which panics:

	Password int `struc:"[3]byte"`

Decoding seems possible, same when using pad instead of byte. Is this a supported operation?

**Comment by lunixbochs** [comment]
You’ll need to make a custom type describing how to pack it

**Comment by andig** [comment]
Great, thank you- wasn‘t even aware that a Packer interface existed. An example would be great, but I think the hint will do ;)

**Comment by lunixbochs** [comment]
Check the other issues for an example
